wait("ff_urlbar.png")
click(Pattern("ff_urlbar.png").targetOffset(-100, 0))
paste("https://www.facebook.com/groups/testmoztext/")
type(Key.ENTER)
setAutoWaitTimeout(10)
wait("facebook_logo.png")
wait("facebook_club_post_area.png")
click(Pattern("facebook_club_post_area.png").targetOffset(0, 15))
paste("Post for delete test!")
click("facebook_post_button.png")
waitVanish("facebook_post_area_focused.png")
sleep(3)
type("r", Key.CTRL)
